require("config.opts")
require("config.keymaps")
require("config.lazy")
require("config.statusline")
require("config.diagnostic")
require("snippets.init")
--require("plugins.node-repl.repl-connector")
